# Generated by Django 2.1.5 on 2019-01-24 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='gender',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
