# Generated by Django 2.1.5 on 2019-01-24 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_shop_gender'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Shop',
            new_name='Item',
        ),
    ]
