# Generated by Django 2.1.5 on 2019-01-27 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_item_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='gender',
            field=models.CharField(choices=[('Men', 'MEN'), ('Women', 'WOMEN'), ('Kids', 'KIDS')], default='Men', max_length=5),
        ),
    ]
