# Generated by Django 2.1.5 on 2019-01-27 16:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0011_auto_20190127_1501'),
    ]

    operations = [
        migrations.CreateModel(
            name='Previoseorders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Userchocie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Item')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Previoseorders')),
            ],
        ),
        migrations.RemoveField(
            model_name='preorders',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userchoose',
            name='item',
        ),
        migrations.RemoveField(
            model_name='userchoose',
            name='name',
        ),
        migrations.DeleteModel(
            name='Preorders',
        ),
        migrations.DeleteModel(
            name='Userchoose',
        ),
    ]
