# Generated by Django 2.1.5 on 2019-01-28 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20190127_1653'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userchocie',
            old_name='name',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='userchocie',
            old_name='number',
            new_name='qauntity',
        ),
    ]
