# Generated by Django 2.1.5 on 2019-01-28 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20190128_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='size',
            field=models.CharField(choices=[('---', '___'), ('Small', 'Small'), ('Medium', 'Medium'), ('Larg', 'Larg')], default='---', max_length=5),
        ),
    ]
