# Generated by Django 2.1.5 on 2019-01-29 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_item_size'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userchocie',
            old_name='qauntity',
            new_name='quantity',
        ),
    ]
