# Generated by Django 2.1.5 on 2019-01-29 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20190129_1653'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userchocie',
            old_name='order',
            new_name='user',
        ),
    ]
