# Generated by Django 2.1.5 on 2019-01-30 16:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20190130_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='previoseorders',
            name='date',
            field=models.DateField(default=datetime.datetime.today),
        ),
    ]
