# Generated by Django 2.1.5 on 2019-02-01 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20190131_0850'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Userchocie',
            new_name='Userchoice',
        ),
    ]
