# Generated by Django 2.1.5 on 2019-01-31 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20190131_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='previoseorders',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
