# Generated by Django 2.1.5 on 2019-01-31 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_auto_20190131_1452'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='previoseorders',
            name='date',
        ),
        migrations.RemoveField(
            model_name='previoseorders',
            name='time',
        ),
    ]
