# Generated by Django 2.1.5 on 2019-01-31 15:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_auto_20190131_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='previoseorders',
            name='date',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2019, 1, 31, 15, 11, 30, 269950, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='previoseorders',
            name='time',
            field=models.TimeField(auto_now_add=True, default=datetime.datetime(2019, 1, 31, 15, 11, 36, 3164, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
