# Generated by Django 2.1.5 on 2019-02-03 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_previoseorders_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='previoseorders',
            name='time',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
