# Generated by Django 2.1.5 on 2019-02-04 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_auto_20190203_1552'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('backgroundImage', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='previoseorders',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='classification',
            field=models.ForeignKey(default=0.0004955401387512388, on_delete=django.db.models.deletion.CASCADE, to='api.Classification'),
            preserve_default=False,
        ),
    ]
