# Generated by Django 2.1.5 on 2019-02-05 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_auto_20190204_1819'),
        ('api', '0018_auto_20190201_1642'),
    ]

    operations = [
    ]
