# Generated by Django 2.1.5 on 2019-02-09 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_merge_20190205_1347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='gender',
        ),
        migrations.AddField(
            model_name='item',
            name='_type',
            field=models.CharField(choices=[('---', '__'), ('TShirts', 'tShirts'), ('Sunglasses', 'sunglasses'), ('Shoes', 'shoes')], default='---', max_length=33),
        ),
    ]
